"""CLAUDE.md generator — synthesizes project rules, entities, and context
into a structured CLAUDE.md file suitable for injection into Claude sessions.

Reads from the rule tree (rules.py) and entity store (store.py) to produce
an auto-generated project configuration file.
"""

from . import store
from .rules import get_all_rules


def generate_claude_md(project: str) -> str:
    """Generate a CLAUDE.md string from the rule tree, entities, and stats.

    Args:
        project: The project name to scope rules and entities to.

    Returns:
        A formatted CLAUDE.md string.
    """
    sections = []
    sections.append(f"# Project Rules (auto-generated by one)\n")
    sections.append(f"Project: {project}\n")

    # ── Rules ──────────────────────────────────────────────────────
    rules = get_all_rules(project)

    if rules:
        # Separate root rules from contextual rules
        root_rules = [r for r in rules if r["parent_id"] is None and r["activation_keywords"] == "*"]
        context_rules = [r for r in rules if r["parent_id"] is None and r["activation_keywords"] != "*"]
        child_rules = [r for r in rules if r["parent_id"] is not None]

        # Build parent -> children map
        children_of: dict[int, list[dict]] = {}
        for r in child_rules:
            children_of.setdefault(r["parent_id"], []).append(r)

        if root_rules:
            sections.append("## Core Rules")
            for r in root_rules:
                sections.append(f"- {r['rule_text']}")
                for child in children_of.get(r["id"], []):
                    sections.append(f"  - {child['rule_text']}")
            sections.append("")

        if context_rules:
            for r in context_rules:
                keywords = r["activation_keywords"]
                sections.append(f"## Context: {keywords}")
                sections.append(f"- {r['rule_text']}")
                for child in children_of.get(r["id"], []):
                    sections.append(f"  - {child['rule_text']}")
                sections.append("")
    else:
        sections.append("## Core Rules")
        sections.append("_No rules defined yet. Use `/rule <text>` to add rules._")
        sections.append("")

    # ── Key Files ──────────────────────────────────────────────────
    file_entities = store.get_entities(entity_type="file", limit=15)
    if file_entities:
        sections.append("## Key Files")
        for ent in file_entities:
            sections.append(f"- {ent['name']} (referenced {ent['observation_count']} times)")
        sections.append("")

    # ── Key Concepts ───────────────────────────────────────────────
    concept_entities = store.get_entities(entity_type="concept", limit=15)
    if concept_entities:
        sections.append("## Key Concepts")
        for ent in concept_entities:
            sections.append(f"- {ent['name']} ({ent['observation_count']} references)")
        sections.append("")

    # ── Key Tools ──────────────────────────────────────────────────
    tool_entities = store.get_entities(entity_type="tool", limit=10)
    if tool_entities:
        sections.append("## Frequently Used Tools")
        for ent in tool_entities:
            sections.append(f"- {ent['name']} ({ent['observation_count']} uses)")
        sections.append("")

    # ── Stats ──────────────────────────────────────────────────────
    st = store.stats()
    sections.append("## Store Stats")
    sections.append(f"- Memories: {st['memories']}")
    sections.append(f"- Entities: {st['entities']}")
    sections.append(f"- Links: {st['links']}")
    sections.append("")

    return "\n".join(sections)
