"""Epistemic Safety Engine — Preventing LLM psychosis in knowledge systems.

The core problem: LLMs generate speculative text that SOUNDS authoritative.
When that text gets stored as "knowledge" and later recalled as context,
it creates a self-reinforcing delusion loop:

  LLM generates speculation → stored as finding → recalled as context →
  LLM treats own speculation as evidence → confidence inflates →
  deeper synthesis builds on hallucinated foundations → "universal patterns"
  emerge from noise → user believes they've discovered something profound

This module enforces epistemic honesty at every stage:
1. PROVENANCE TRACKING — every claim tagged with its actual source
2. CONFIDENCE CEILINGS — LLM-generated content can never self-verify above limits
3. CIRCULAR REFERENCE DETECTION — catches the self-reinforcement loop
4. EPISTEMIC MARKERS — uncertainty language injected into all stored content
5. REALITY ANCHORING — distinguishes empirical facts from LLM confabulation
"""

import re
from typing import Optional


# ── Provenance tags ──────────────────────────────────────────────

class Provenance:
    """Source classification for knowledge claims."""
    EMPIRICAL = "empirical"            # From actual data, experiments, observations
    PEER_REVIEWED = "peer_reviewed"    # From peer-reviewed literature (cited)
    LLM_GENERATED = "llm_generated"   # Generated by an LLM (Gemma, Claude, etc.)
    LLM_SYNTHESIS = "llm_synthesis"    # LLM combining other LLM outputs
    USER_STATED = "user_stated"        # User directly said this
    TOOL_OUTPUT = "tool_output"        # From code execution, search results, etc.
    UNVERIFIED = "unverified"          # Unknown provenance


# Maximum confidence an LLM-generated claim can reach through self-verification.
# An LLM verifying its own output is NOT independent verification.
LLM_SELF_VERIFY_CEILING = 0.60

# Maximum confidence for LLM synthesis (hypothesis built on other LLM outputs).
# Stacking speculation on speculation doesn't increase reliability.
LLM_SYNTHESIS_CEILING = 0.45

# Maximum confidence for deep synthesis (meta-hypotheses from hypotheses).
# Each layer of abstraction WITHOUT empirical grounding loses reliability.
LLM_DEEP_SYNTHESIS_CEILING = 0.35

# Confidence penalty per depth level for recursive synthesis.
DEPTH_CONFIDENCE_DECAY = 0.10

# Minimum number of INDEPENDENT (non-LLM) sources to consider something
# "corroborated" vs just "an LLM said it twice."
MIN_INDEPENDENT_SOURCES = 2


# ── Epistemic markers ────────────────────────────────────────────

UNCERTAINTY_PREFIXES = {
    Provenance.LLM_GENERATED: "[LLM-GENERATED HYPOTHESIS] ",
    Provenance.LLM_SYNTHESIS: "[LLM-SYNTHESIZED — NOT EMPIRICALLY VERIFIED] ",
    Provenance.UNVERIFIED: "[UNVERIFIED CLAIM] ",
}

# Phrases that indicate an LLM is performing false certainty
FALSE_CERTAINTY_PATTERNS = [
    re.compile(r'\bthis (?:proves?|confirms?|demonstrates?|establishes?) that\b', re.I),
    re.compile(r'\bwe (?:now know|can confirm|have established) that\b', re.I),
    re.compile(r'\bthe evidence (?:clearly |conclusively )?(?:shows?|proves?|demonstrates?)\b', re.I),
    re.compile(r'\bundeniable|irrefutable|beyond doubt|without question\b', re.I),
    re.compile(r'\bdefinitively (?:shows?|proves?|confirms?)\b', re.I),
    re.compile(r'\bthis is a (?:breakthrough|paradigm shift|revolutionary)\b', re.I),
    re.compile(r'\bno one has (?:ever|previously) (?:seen|noticed|discovered)\b', re.I),
    re.compile(r'\bfor the first time (?:ever|in history)\b', re.I),
]

# Phrases that indicate genuine epistemic humility
HONEST_UNCERTAINTY_PATTERNS = [
    re.compile(r'\b(?:may|might|could|possibly|perhaps|likely|suggests?)\b', re.I),
    re.compile(r'\bhypothesis|speculation|conjecture|tentative\b', re.I),
    re.compile(r'\bif (?:true|correct|verified|confirmed)\b', re.I),
    re.compile(r'\bneeds? (?:further|additional|independent) (?:verification|testing|evidence)\b', re.I),
    re.compile(r'\blimitation|caveat|uncertainty|unclear\b', re.I),
    re.compile(r'\bcorrelation.{0,20}causation\b', re.I),
]


# ── Core safety functions ────────────────────────────────────────


def classify_provenance(text: str, source: str) -> str:
    """Classify the provenance of a piece of text.

    Returns one of the Provenance constants based on the source tag
    and content analysis.
    """
    if source in ("user", "human"):
        return Provenance.USER_STATED
    if source in ("tool_result", "tool_output", "search"):
        return Provenance.TOOL_OUTPUT
    if source in ("synthesis", "dialectic", "meta_synthesis"):
        return Provenance.LLM_SYNTHESIS
    if source in ("research", "hypothesis", "gemma", "ollama", "claude"):
        return Provenance.LLM_GENERATED

    # Content-based detection
    lower = text.lower()
    llm_signals = [
        "hypothesis:", "meta-hypothesis:", "synthesis:",
        "based on the analysis", "given the above",
        "this suggests that", "the pattern indicates",
    ]
    if any(sig in lower for sig in llm_signals):
        return Provenance.LLM_GENERATED

    # Check for empirical markers
    empirical_signals = [
        r'\bp\s*[<>=]\s*0\.\d+',
        r'\bn\s*=\s*\d{2,}',
        r'\bCI\s*[\[:(]\d',
        r'\bdoi:\s*10\.\d+',
        r'\bPMID:\s*\d+',
    ]
    if any(re.search(sig, text) for sig in empirical_signals):
        return Provenance.EMPIRICAL

    return Provenance.UNVERIFIED


def apply_confidence_ceiling(
    confidence: float,
    provenance: str,
    depth: int = 0,
) -> float:
    """Apply confidence ceilings based on provenance and synthesis depth.

    An LLM cannot verify itself above the ceiling. Deeper synthesis layers
    get progressively lower ceilings because each abstraction layer without
    empirical grounding compounds uncertainty.
    """
    if provenance == Provenance.EMPIRICAL:
        return confidence  # No ceiling for empirical data
    if provenance == Provenance.PEER_REVIEWED:
        return min(confidence, 0.90)
    if provenance == Provenance.USER_STATED:
        return min(confidence, 0.85)
    if provenance == Provenance.TOOL_OUTPUT:
        return min(confidence, 0.80)

    if provenance == Provenance.LLM_SYNTHESIS:
        ceiling = LLM_SYNTHESIS_CEILING - (depth * DEPTH_CONFIDENCE_DECAY)
        return min(confidence, max(0.10, ceiling))

    # LLM-generated or unverified
    if depth > 0:
        ceiling = LLM_DEEP_SYNTHESIS_CEILING - ((depth - 1) * DEPTH_CONFIDENCE_DECAY)
        return min(confidence, max(0.10, ceiling))

    return min(confidence, LLM_SELF_VERIFY_CEILING)


def detect_false_certainty(text: str) -> list[str]:
    """Detect phrases where an LLM is expressing false certainty.

    Returns list of matched phrases. If non-empty, the text should be
    flagged or have its confidence reduced.
    """
    matches = []
    for pattern in FALSE_CERTAINTY_PATTERNS:
        found = pattern.findall(text)
        matches.extend(found)
    return matches


def score_epistemic_honesty(text: str) -> float:
    """Score how epistemically honest a piece of text is.

    0.0 = maximally overconfident (many false certainty signals, no hedging)
    1.0 = appropriately uncertain (hedges present, no false certainty)

    This does NOT penalize genuine confidence backed by evidence.
    Text with citations + appropriate hedging scores highest.
    """
    false_cert_count = len(detect_false_certainty(text))
    honest_count = sum(
        1 for p in HONEST_UNCERTAINTY_PATTERNS if p.search(text)
    )

    # Check for actual citations (DOIs, PMIDs, specific study references)
    citation_patterns = [
        r'\bdoi:\s*10\.\d+', r'\bPMID:\s*\d+', r'\(\d{4}\)',
        r'\bet al\.', r'\baccording to\b',
    ]
    citation_count = sum(1 for p in citation_patterns if re.search(p, text))

    if false_cert_count == 0 and honest_count == 0:
        return 0.5  # Neutral

    # Base score from ratio of honesty to false certainty
    total = false_cert_count + honest_count
    if total == 0:
        base = 0.5
    else:
        base = honest_count / total

    # Citations boost the score (earned confidence is fine)
    citation_bonus = min(0.2, citation_count * 0.05)

    return min(1.0, base + citation_bonus)


def detect_circular_reference(
    text: str,
    source: str,
    existing_memories: list[dict],
) -> bool:
    """Detect when an LLM is treating its own prior output as independent evidence.

    This is the core of the self-reinforcement loop:
    - LLM generates hypothesis H
    - H gets stored as memory
    - Later, H is recalled as "existing knowledge"
    - LLM cites H as evidence for a new claim that's basically H restated

    Returns True if circular reference detected.
    """
    if source not in ("synthesis", "dialectic", "research", "hypothesis",
                       "gemma", "ollama", "claude"):
        return False

    from .hdc import encode_text, similarity

    text_vec = encode_text(text)

    for mem in existing_memories:
        # Only check LLM-generated prior memories
        mem_source = mem.get("source", "")
        if mem_source not in ("synthesis", "dialectic", "research",
                               "hypothesis", "gemma", "ollama", "claude"):
            continue

        mem_text = mem.get("raw_text", "")
        if not mem_text:
            continue

        mem_vec = encode_text(mem_text)
        sim = float(similarity(text_vec, mem_vec))

        # High similarity between two LLM-generated pieces = circular
        if sim > 0.75:
            return True

    return False


def add_epistemic_marker(text: str, provenance: str) -> str:
    """Prepend an epistemic marker to text based on its provenance.

    This ensures that when knowledge is recalled as context, the LLM
    and user can see WHERE the claim came from and how much to trust it.
    """
    prefix = UNCERTAINTY_PREFIXES.get(provenance, "")
    if prefix and not text.startswith("["):
        return prefix + text
    return text


def sanitize_for_storage(
    text: str,
    source: str,
    confidence: float,
    existing_memories: Optional[list[dict]] = None,
    depth: int = 0,
) -> dict:
    """Full safety pipeline for content before it enters the knowledge graph.

    Returns dict with:
    - text: sanitized text with epistemic markers
    - confidence: ceiling-adjusted confidence
    - provenance: classified source type
    - blocked: whether storage should be blocked entirely
    - block_reason: why it was blocked (if applicable)
    - warnings: list of safety warnings
    """
    provenance = classify_provenance(text, source)
    warnings = []

    # Apply confidence ceiling
    original_confidence = confidence
    confidence = apply_confidence_ceiling(confidence, provenance, depth)
    if confidence < original_confidence:
        warnings.append(
            f"confidence capped {original_confidence:.2f} → {confidence:.2f} "
            f"(provenance: {provenance}, depth: {depth})"
        )

    # Detect false certainty
    false_cert = detect_false_certainty(text)
    if false_cert:
        confidence = max(0.10, confidence - 0.15)
        warnings.append(
            f"false certainty detected: {false_cert[:3]}; "
            f"confidence reduced to {confidence:.2f}"
        )

    # Score epistemic honesty
    honesty = score_epistemic_honesty(text)
    if honesty < 0.3:
        confidence = max(0.10, confidence - 0.10)
        warnings.append(
            f"low epistemic honesty ({honesty:.2f}); "
            f"confidence reduced to {confidence:.2f}"
        )

    # Circular reference detection
    blocked = False
    block_reason = ""
    if existing_memories and detect_circular_reference(text, source, existing_memories):
        blocked = True
        block_reason = (
            "circular reference: LLM output is too similar to existing "
            "LLM-generated memory — storing would create self-reinforcing loop"
        )
        warnings.append(block_reason)

    # Add epistemic marker
    marked_text = add_epistemic_marker(text, provenance)

    return {
        "text": marked_text,
        "confidence": confidence,
        "provenance": provenance,
        "blocked": blocked,
        "block_reason": block_reason,
        "warnings": warnings,
    }


# ── Safety prompts for injection into LLM contexts ──────────────

EPISTEMIC_SAFETY_PROMPT = """EPISTEMIC SAFETY RULES — NON-NEGOTIABLE:

1. YOU ARE AN LLM. Your outputs are PROBABILISTIC TEXT GENERATION, not knowledge.
   Never present your generated text as established fact.

2. CONFIDENCE ≠ TRUTH. Just because you can generate a fluent, confident-sounding
   paragraph does not make it true. Hedge appropriately.

3. SELF-VERIFICATION IS NOT VERIFICATION. You cannot verify your own outputs.
   An LLM checking its own work is like grading your own exam — it finds what
   it expects to find. Only INDEPENDENT evidence (empirical data, peer-reviewed
   sources, tool outputs) counts as verification.

4. SYNTHESIS IS SPECULATION. When you combine two findings into a "hypothesis,"
   you are speculating, not discovering. Label it as such. The word "suggests"
   is almost always more honest than "shows" or "demonstrates."

5. DEPTH INCREASES UNCERTAINTY. Each layer of abstraction from raw data
   INCREASES uncertainty, it does not decrease it. A "meta-synthesis of
   syntheses" is LESS reliable than the individual findings, not more.

6. CITE OR CAVEAT. If you can cite a specific study, dataset, or empirical
   result, do so. If you cannot, explicitly say "this is LLM-generated
   speculation, not an empirically verified claim."

7. THE MAP IS NOT THE TERRITORY. Your knowledge graph is a MODEL of reality,
   not reality itself. Connections you find between entities may be artifacts
   of how language models represent information, not real-world relationships.

8. BEWARE PATTERN MATCHING MASQUERADING AS INSIGHT. LLMs are exceptionally
   good at finding "patterns" — including in noise. A compelling narrative
   connecting two concepts is not evidence of a real connection.

9. NO GRANDIOSE CLAIMS. Do not describe findings as "breakthrough,"
   "revolutionary," "paradigm-shifting," "no one has ever noticed," or
   "this changes everything" unless citing specific external evidence.

10. ALWAYS INCLUDE WHAT COULD BE WRONG. For every hypothesis, state at least
    one way it could be false. If you cannot think of how it could be wrong,
    you are not thinking hard enough."""


CONTEXT_INJECTION_WARNING = """⚠ KNOWLEDGE CONTEXT WARNING:
The memories/findings below were recalled from the knowledge graph.
Some may be LLM-GENERATED content from prior sessions — not independently
verified facts. Treat items tagged [LLM-GENERATED] or [LLM-SYNTHESIZED]
as HYPOTHESES to be tested, not facts to build upon. Check provenance
tags before treating any recalled content as evidence."""
